# Generated by Django 5.0.14 on 2026-06-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='municipio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
