# Generated by Django 5.0.14 on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_perfil_codigo_postal_perfil_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario normal'), ('admin', 'Administrador')], default='usuario', max_length=20),
        ),
    ]
