# Generated by Django 4.2 on 2026-06-19 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_perfil_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaForo',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_foro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tema de foro',
                'verbose_name_plural': 'Temas de foro',
                'db_table': 'tema_foro',
                'ordering': ['-fecha_publicacion', '-id_tema'],
            },
        ),
        migrations.AddIndex(
            model_name='temaforo',
            index=models.Index(fields=['id_usuario', 'fecha_publicacion'], name='idx_tema_foro_usuario_fecha'),
        ),
    ]
