# Generated by Django 4.2 on 2026-06-20 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_temaforo_temaforo_idx_tema_foro_usuario_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaccionForo',
            fields=[
                ('id_reaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('me_gusta', 'Me gusta'), ('no_me_gusta', 'No me gusta')], max_length=20)),
                ('fecha_reaccion', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id_tema', models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='website.temaforo')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reacciones_foro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reacción de foro',
                'verbose_name_plural': 'Reacciones de foro',
                'db_table': 'reaccion_foro',
                'ordering': ['-fecha_reaccion', '-id_reaccion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioForo',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('id_tema', models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='website.temaforo')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_foro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de foro',
                'verbose_name_plural': 'Comentarios de foro',
                'db_table': 'comentario_foro',
                'ordering': ['fecha_comentario'],
            },
        ),
        migrations.AddIndex(
            model_name='reaccionforo',
            index=models.Index(fields=['id_tema', 'tipo'], name='idx_reaccion_tema_tipo'),
        ),
        migrations.AddIndex(
            model_name='reaccionforo',
            index=models.Index(fields=['id_usuario', 'tipo'], name='idx_reaccion_usuario_tipo'),
        ),
        migrations.AddConstraint(
            model_name='reaccionforo',
            constraint=models.UniqueConstraint(fields=('id_tema', 'id_usuario'), name='uniq_tema_usuario_reaccion'),
        ),
        migrations.AddIndex(
            model_name='comentarioforo',
            index=models.Index(fields=['id_tema', 'fecha_comentario'], name='idx_comentario_tema_fecha'),
        ),
    ]
