# Generated by Django 4.2 on 2026-06-20 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_reaccionforo_comentarioforo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaForo',
            fields=[
                ('id_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha_denuncia', models.DateTimeField(auto_now_add=True)),
                ('id_tema', models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='website.temaforo')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_foro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denuncia de foro',
                'verbose_name_plural': 'Denuncias de foro',
                'db_table': 'denuncia_foro',
                'ordering': ['-fecha_denuncia', '-id_denuncia'],
            },
        ),
        migrations.AddIndex(
            model_name='denunciaforo',
            index=models.Index(fields=['id_tema', 'fecha_denuncia'], name='idx_denuncia_tema_fecha'),
        ),
        migrations.AddConstraint(
            model_name='denunciaforo',
            constraint=models.UniqueConstraint(fields=('id_tema', 'id_usuario'), name='uniq_tema_usuario_denuncia'),
        ),
    ]
