# Generated by Django 4.2 on 2026-06-20 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_denunciaforo_denunciaforo_idx_denuncia_tema_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdministrador',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_admin_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_admin_enviadas', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de administrador',
                'verbose_name_plural': 'Solicitudes de administrador',
                'db_table': 'solicitud_administrador',
                'ordering': ['-fecha_solicitud', '-id_solicitud'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudadministrador',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='idx_solicitud_estado_fecha'),
        ),
    ]
